[tool.poetry]
name = "guardrails-ai"
version = "0.4.5"
description = "Adding guardrails to large language models."
authors = ["Guardrails AI <contact@guardrailsai.com>"]
license = "Apache License 2.0"
homepage = "https://www.guardrailsai.com/"
documentation = "https://www.guardrailsai.com/docs"
readme = "README.md"
packages = [
    { include = "guardrails", from = "." }
]

[tool.poetry.scripts]
guardrails = "guardrails.cli:cli"

[tool.poetry.dependencies]
python = "^3.8.1"
alt-profanity-check = {version = "^1.3.1", optional = true}
anthropic = {version = "^0.7.2", optional = true}
coloredlogs = "^15.0.1"
detect-secrets = {version = "^1.4.0", optional = true}
docspec_python = "2.2.1"
faiss-cpu = {version = "^1.7.4", optional = true}
griffe = "^0.36.9"
guardrails-api-client = "^0.2.1"
huggingface_hub = {version = "^0.19.3", optional = true}
langchain-core = ">=0.1,<0.3"
litellm = {version = "^1.37.14", optional = true}
lxml = "^4.9.3"
manifest-ml = {version = "^0.1.8", optional = true}
nbdoc = {version = "^0.0.82", optional = true}
nltk = "^3.8.1"
numpy = {version = ">=1.24", optional = true}
openai = "^1.30.1"
opentelemetry-exporter-otlp-proto-grpc = "^1.24.0"
opentelemetry-exporter-otlp-proto-http = "^1.24.0"
opentelemetry-sdk = "^1.24.0"
pip = ">=22"
presidio_analyzer = {version = "^2.2.33", optional = true}
presidio_anonymizer = {version = "^2.2.33", optional = true}
pydantic = ">=1.10.9, <3.0"
pydash = "^7.0.6"
pydoc-markdown = "4.8.2"
pyjwt = "^2.8.0"
python-dateutil = "^2.8.2"
regex = "^2023.10.3"
requests = "^2.31.0"
rich = "^13.6.0"
rstr = "^3.2.2"
spacy-transformers = {version = "^1.3.4", optional = true}
sqlalchemy = {version = ">=2.0.9", optional = true}
sqlglot = {version = "^19.0.3", optional = true}

sqlvalidator = {version = "^0.0.20", optional = true}
tenacity = ">=8.1.0"
thefuzz = {version = "^0.20.0", optional = true}
tiktoken = ">=0.5.1"
torch = {version = "^2.1.1", optional = true}
transformers = {version = "^4.36.0", optional = true}
typer = {extras = ["all"], version = "^0.9.0"}
typing-extensions = "^4.8.0"
unbabel-comet = {version = "^2.2.1", optional = true}

[tool.poetry.extras]
sql = ["sqlvalidator", "sqlalchemy", "sqlglot"]
summary = ["thefuzz"]
vectordb = ["faiss-cpu", "numpy"]
profanity = ["alt-profanity-check"]
detect-secrets = ["detect-secrets"]
manifest = ["manifest-ml"]
litellm = ["litellm"]
high_quality_translation = ["unbabel-comet", "huggingface_hub"]
toxic_language = ["transformers", "torch"]
pii = ["presidio_analyzer", "presidio_anonymizer"]
competitor-check = ["spacy-transformers"]
anthropic = ["anthropic"]
docs-build = ["nbdoc", "docspec_python", "pydoc-markdown"]


[tool.poetry.group.dev.dependencies]
docformatter = ">=1.4"
lxml-stubs = "^0.4.0"
pre-commit = ">=2.9.3"
pypdfium2 = "^4.23.1"
pyright = "1.1.334"
pytest = "^7.4.3"
pytest-asyncio = "^0.21.1"
pytest-cov = ">=2.10.1"
pytest-mock = "^3.12.0"
ruff = ">=0.4.1"
twine = "^4.0.2"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
cairosvg = "^2.7.1"
griffe = "^0.36.9"
mkdocs = "^1.5.3"
mkdocs-glightbox = "^0.3.4"
mkdocs-jupyter = ">=0.23"
mkdocs-material = "^9.4.8"
mkdocstrings = {extras = ["python"], version = "^0.23.0"}
mknotebooks = "^0.8.0"
pillow = "^10.1.0"

[[tool.poetry.source]]
name = "PyPI"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "E501"]
ignore = ["E731", "E203", "E741"]